slam_toolbox:
  ros__parameters:
    use_sim_time: false  # Adjust if using a simulated environment
    database_path: "/home/indro/colcon_ws/src/scout_commander/scout_mini_control/maps/map.db"
    resolution: 0.05     # Map resolution in meters per cell
    max_laser_range: 16.0  # Adjust based on your LiDAR's maximum range
    minimum_time_interval: 0.2  # Minimum interval between scans in seconds
    mode: "mapping"      # Can be "mapping" or "localization" (adjust when switching modes)

    # SLAM Algorithm Parameters
    scan_topic: "/scan"  # Ensure it matches the LiDAR scan topic
    odom_frame: "odom"             # Odom frame
    map_frame: "map"               # Map frame
    base_frame: "base_footprint"   # Base frame of your robot
    publish_frame_projected_to_2d: true
    transform_tolerance: 0.2

    # Optimizations
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.785  # ~45 degrees
    maximum_iterations: 10000
    max_submaps: 10
    fresh_map: false
    localization_mode: false  # Set true if running in localization mode
    allow_scan_matching: true
    allow_loop_closing: true

    # Save/Load Map
    map_save_duration: 60.0  # Save map every 60 seconds
    use_scan_matching: true
    use_loop_closing: true

